### ISSUE TITLE
[BUG] Client log spam on SkinHelper:getBufferedImageSkin

### ISSUE THREAD

**Issue by LemADEC** [Armourers-Workshop/Armourers-Workshop#336]
**Describe the bug**
As of Armourers-Workshop-1.12.2-0.50.3, client logs are spammed with file not found exception, generating ~400MB of logs per hour.
```
[02:49:42] [Client thread/INFO]: [moe.plushie.armourers_workshop.common.SkinHelper:getBufferedImageSkin:70]: java.io.FileNotFoundException: armourers_workshop:923475630
[02:49:42] [Client thread/INFO]: [moe.plushie.armourers_workshop.common.SkinHelper:getBufferedImageSkin:70]: 	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69)
[02:49:42] [Client thread/INFO]: [moe.plushie.armourers_workshop.common.SkinHelper:getBufferedImageSkin:70]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65)
[02:49:42] [Client thread/INFO]: [moe.plushie.armourers_workshop.common.SkinHelper:getBufferedImageSkin:70]: 	at moe.plushie.armourers_workshop.common.SkinHelper.getBufferedImageSkin(SkinHelper.java:66)
[02:49:42] [Client thread/INFO]: [moe.plushie.armourers_workshop.common.SkinHelper:getBufferedImageSkin:70]: 	at moe.plushie.armourers_workshop.client.render.EntityTextureInfo.updateTexture(EntityTextureInfo.java:94)
[02:49:42] [Client thread/INFO]: [moe.plushie.armourers_workshop.common.SkinHelper:getBufferedImageSkin:70]: 	at moe.plushie.armourers_workshop.client.handler
```

**To Reproduce**
1. Nothing special, just mining around in a 2 player server

**Expected behavior**
No log spam

**Screenshots**
n/a

**Additional context**
It's observed in test modpack with 198 other mods.
I suspect it could be a conflict with JJ Races 1.12-1.12.2-v1.0.14.

**Comment by RiskyKen** [comment]
Am guessing some mod is having issues with AWs texture painting system. You can change `texturePaintingType` in `config/armourers_workshop/client.cfg`

Setting it to `-1` will disable that part of the mod.

You can also try setting it to `3`, this will used the newer experimental code. There may be bugs as this has not been tested much yet.

**Comment by LemADEC** [comment]
The modpack was updated with texturePaintingType=3 and, so far, issue wasn't reproduced.
