### ISSUE TITLE
[CRASH] On Fabric 1.19.4 (0.14.19) with Armourers Workshop 2.0.0-Beta 19: NoClassDefFoundError: org/lwjgl/BufferUtils

### ISSUE THREAD

**Issue by pavog** [Armourers-Workshop/Armourers-Workshop#403]
**To Reproduce**
Steps to reproduce the crash:
1. Install a fresh new server with Fabric 1.19.4 (0.14.19)
2. Install Armourers Workshop 1.19.4 2.0.0 Beta 19 ([armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar](https://www.curseforge.com/minecraft/mc-mods/armourers-workshop/files/4537939))
3. Install Fabric API 0.81.1+1.19.4 ([fabric-api-0.81.1+1.19.4.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4538872))
4. Run the server with Java 17
5. See error

**Crash log**
```
[main/ERROR]: Failed to start the minecraft server
--
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'armourers_workshop'!
 at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.19.jar:?]
 at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.19.jar:?]
 at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.19.jar:?]
 at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.19.jar:?]
 at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.19.jar:?]
 at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
 at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
 at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
 at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.19.jar:?]
 at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.19.jar:?]
 Caused by: java.lang.NoClassDefFoundError: org/lwjgl/BufferUtils
 at moe.plushie.armourers_workshop.utils.ObjectUtils.<clinit>(ObjectUtils.java:19) ~[armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar:?]
 at moe.plushie.armourers_workshop.compatibility.fabric.AbstractFabricRegistry.<init>(AbstractFabricRegistry.java:26) ~[armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar:?]
 at extensions.net.minecraft.core.Registry.FabricProvider.<clinit>(FabricProvider.java:43) ~[armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar:?]
 at moe.plushie.armourers_workshop.init.platform.fabric.builder.ItemGroupBuilderImpl$ItemGroup.<init>(ItemGroupBuilderImpl.java:43) ~[armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar:?]
 at moe.plushie.armourers_workshop.init.platform.fabric.builder.ItemGroupBuilderImpl.build(ItemGroupBuilderImpl.java:34) ~[armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar:?]
 at moe.plushie.armourers_workshop.init.platform.fabric.builder.ItemGroupBuilderImpl.build(ItemGroupBuilderImpl.java:19) ~[armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar:?]
 at moe.plushie.armourers_workshop.init.ModItemGroups.<clinit>(ModItemGroups.java:12) ~[armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar:?]
 at moe.plushie.armourers_workshop.ArmourersWorkshop.init(ArmourersWorkshop.java:37) ~[armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar:?]
 at moe.plushie.armourers_workshop.init.platform.fabric.proxy.CommonProxyImpl.onInitialize(CommonProxyImpl.java:42) ~[armourersworkshop-fabric-1.19.4-2.0.0-beta.19.jar:?]
 at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.19.jar:?]
 ... 7 more
```

Full crash log: https://mclo.gs/aJqK7qn

**Comment by SAGESSE-CN** [comment]
fixed in dev.181
